spring.application.name=digitalwallet
spring.datasource.url=jdbc:mysql://localhost:3306/digital_wallet
spring.datasource.username=root
spring.datasource.password=sql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
spring.devtools.restart.enabled=false
server.shutdown=graceful